# Generated by Django 3.2.25 on 2025-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word_Trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
