# Generated by Django 3.2.25 on 2025-07-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word_Trainer', '0003_userword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userword',
            name='score',
        ),
    ]
